name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FRONTEND_IMAGE: "arryuannkhanna/react-frontend"
  BACKEND_IMAGE: "arryuannkhanna/my-django-backend"
  DOCKER-TAG: "latest"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./e-comm-frontend
        run: |
          npm install
          npm run build

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Buil backend
        working-directory: ./ecomm-django-backend
        run:  |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          python 
          
  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to the docker hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Docker Image
        working-directory: ./e-comm-frontend
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker push ${{ env.FRONTEND_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Build and Push Backend Docker Image
        working-directory: ./ecomm-django-backend
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker push ${{ env.BACKEND_IMAGE }}:${{ env.DOCKER_TAG }}
  
          
